version: '2'

services:
  db:
    build: chronix
    ports:
      - 8983
    volumes:
      - data:/data
      - config:/conf
    restart: unless-stopped

  ingester:
    build: ingester
    ports:
      - 8080
    links:
      - db:chronix
    restart: unless-stopped

volumes:
  data:
  config:
